<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <SmokePackageVersion Condition="'$(SmokePackageVersion)' == ''">0.0.0-ci</SmokePackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Endfix.Telegram.BotAPI" Version="$(SmokePackageVersion)" />
  </ItemGroup>

</Project>
