<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>139acb28-9f5d-49e2-b8b0-69f07e1839b6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Telegram.BotAPI\Telegram.BotAPI.csproj" />
  </ItemGroup>

</Project>
