<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>		
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<IsPackable>true</IsPackable>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
	  <PackageReference Include="System.Text.Json" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="BotApiClient.*.cs">
			<DependentUpon>BotApiClient.cs</DependentUpon>
		</Compile>
	</ItemGroup>
	
</Project>
